# Page content type
synapse_page_accorhotel_content:
    path: "/{path}.{_format}"
    defaults:
        _controller: "SynapseAccorHotelPageBundle:Promotions:render"
        _format: html
    requirements:
        path: "[^.]*"