# Page content type
synapse_content_type_page:
    path: "/{path}.{_format}"
    defaults:
        _controller: "SynapseAccorHotelAppBundle:PageContent:render"
        _format: html
    requirements:
        path: "[^.]*"
